# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Personal Subscription(e59d4a87-0808-41fc-9ae0-343de510f79e)'
    command: 'build'
    projects: '/webapp/webapp.csproj'
    workingDirectory: '/webapp/'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'webapp'
    publishLocation: 'Container'