# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: '$(_PersonalSubscription)'
    command: 'build'
    projects: 'webapp/webapp.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'webapp/webapp.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'webapp'
    publishLocation: 'Container'
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: '$(_PersonalSubscription)'
    Action: 'Stop Azure App Service'
    WebAppName: '$(WebAppName)'
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(_PersonalSubscription)'
    appType: 'webAppLinux'
    WebAppName: '$(WebAppName)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|8.0'
    DeploymentTypeLinux: 'oneDeploy'
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: '$(_PersonalSubscription)'
    Action: 'Start Azure App Service'
    WebAppName: '$(WebAppName)'